FROM onesysadmin/grails:1.1.1-SNAPSHOT

ENV GWT_HOME /usr/local/gwt-linux-1.5.3

# Install GWT
WORKDIR /usr/local
RUN wget -O - --quiet https://github.com/asans/appdist-archive/blob/master/gwt/gwt-linux-1.5.3.tar.bz2?raw=true | tar xjf -

